### ISSUE TITLE
Is it possible to not clear everything after running the app?

### ISSUE THREAD

**Issue by jcubic** [beetcb/enhanced-readline#4]
This is not how every REPL works I don't know even single REPL that would clear the screen before printing the prompt.

Is there a way to disable this?

**Comment by yaonyan** [comment]
Yes! That makes sence, I fix it in `repll@1.2.7`, update the package to try it 🎉 @jcubic

**Comment by yaonyan** [comment]
And still, i can't believe heightlight is not working, i updated it in the version(1.2.8). 
Plz do see my proof at [repll.it](https://repl.it/talk/share/repll-heightlight/116960)
![repl.it](https://user-images.githubusercontent.com/63141491/105618495-c449c500-5e22-11eb-917c-dfb6b80ac70d.gif)

**Comment by jcubic** [comment]
It seems that you use two API interchangeably but they are not the same, argument to onInput is single character not whole string. As of now every example you show me was using this API and now you show `repll.input` .

**Comment by yaonyan** [comment]
Yeah! the `repll.input` keeps track of user's input in current line, perhaps I didn't make it clear in readme
Now I see, you were doing some REGEXP test on `onInput` callback's argument, that's for single charactor or paste text only

**Comment by yaonyan** [comment]
Believe me, a careful reading of [`readme`](https://github.com/beetcb/repll/blob/master/README.md) would make you life much more easier @jcubic

And this(Is it possible to not clear everything after running the app?) still have a bug for now, when the output hit the bottom of the page, cursor's position start to dislocate.

**Comment by jcubic** [comment]
Nice that you have readme but `you've posted the answer on StackOverflow` that was not working because it used the argument.

**Comment by yaonyan** [comment]
I thought you were only detecting user pasted content
Nevermind, forget it ☺.

**Comment by yaonyan** [comment]
> still have a bug for now, when the output hit the bottom of the page, cursor's position start to dislocate.

fixed, now repll@1.3.0 works like a charm now!
